name: 'Update Helm App Version'
description: 'Updates the app version in the specified Helm values file and pushes the change.'
inputs:
  app_name:
    description: 'The name of the application (e.g., krew-test-app-api)'
    required: true
  environment:
    description: 'The environment to update (e.g., integration-sandbox, integration)'
    required: true
  version:
    description: 'The new version tag'
    required: true
  token:
    description: 'GitHub token with push access (e.g. from a GitHub App)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
  - name: Update values file
    shell: bash
    run: |
      FILE_PATH="helm/apps/${{ inputs.app_name }}/values/appversion-${{ inputs.environment }}.values.yaml"
      echo "Updating $FILE_PATH with version ${{ inputs.version }}"

      # Check if file exists
      if [ ! -f "$FILE_PATH" ]; then
        echo "File $FILE_PATH does not exist!"
        exit 1
      fi

      # Update the tag using sed. Assuming the format is "  tag: <version>"
      # Use a temporary file to handle sed differences between macOS and Linux if running locally, 
      # but in GitHub Actions (Linux) -i works. 
      # To be safe and robust against whitespace:
      sed -i 's/tag: .*/tag: ${{ inputs.version }}/' "$FILE_PATH"

      # Verify the change
      cat "$FILE_PATH"

  - name: Commit and Push changes
    shell: bash
    env:
      INPUT_TOKEN: ${{ inputs.token }}
    run: |
      git config --global user.name "github-actions[bot]"
      git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # If a custom token is provided, update the remote URL to use it
      if [[ -n "$INPUT_TOKEN" ]]; then
        REPO_URL=$(git remote get-url origin | sed 's|https://.*@|https://|' | sed 's|https://|https://x-access-token:'"$INPUT_TOKEN"'@|')
        git remote set-url origin "$REPO_URL"
      fi

      FILE_PATH="helm/apps/${{ inputs.app_name }}/values/appversion-${{ inputs.environment }}.values.yaml"

      git add "$FILE_PATH"

      # Check if there are changes to commit
      if git diff --staged --quiet; then
        echo "No changes to commit."
      else
        git commit -m "chore: update ${{ inputs.app_name }} version to ${{ inputs.version }} for ${{ inputs.environment }}"
        
        MAX_RETRIES=10
        count=0
        success=false

        while [ $count -lt $MAX_RETRIES ]; do
          git pull --rebase origin main
          if git push origin HEAD:main; then
            success=true
            break
          else
            echo "Push failed, retrying in 5 seconds..."
            sleep 5
            count=$((count + 1))
          fi
        done

        if [ "$success" = false ]; then
          echo "Failed to push changes after $MAX_RETRIES attempts."
          exit 1
        fi
      fi
